repos:

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: check-added-large-files
    name: check for added large files
    description: prevents giant files from being committed.
    entry: check-added-large-files
    language: python
    stages: [commit, push, manual]

  - id: check-executables-have-shebangs
    name: check that executables have shebangs
    description: ensures that (non-binary) executables have a shebang.
    entry: check-executables-have-shebangs
    language: python
    types: [text, executable]
    stages: [commit, push, manual]

#   - id: check-yaml
#     name: check yaml
#     description: checks yaml files for parseable syntax.
#     entry: check-yaml
#     args: ["--allow-multiple-documents"]
#     language: python
#     exclude: '.ytt.yaml$'
#     types: [yaml]
# 
#   - id: shell-fmt-go
#     name: shfmt
#     description: Rewrites all shell scripts to a canonical format.
#     language: golang
#     additional_dependencies:
#       - mvdan.cc/sh/v3/cmd/shfmt@v3.4.3
#     entry: shfmt
#     types:
#       - file
#       - shell
#     exclude_types:
#       - zsh
#     args:
#       - -w
#       - -s
#       - -l
#       - -i
#       - "4"
# 
# 
# - repo: https://github.com/scop/pre-commit-shfmt
#   rev: v3.6.0-1
#   hooks:
#     # Choose one of:
#     - id: shfmt 
# 

- repo: local
  hooks:
    - id: shfmt
      name: shfmt
      entry: shfmt -w -i 4
      language: golang
      additional_dependencies: [mvdan.cc/sh/v3/cmd/shfmt@v3.4.3]
      types: [shell]

    - id: actionlint
      name: actionlint
      entry: actionlint
      language: golang
      additional_dependencies: [github.com/rhysd/actionlint/cmd/actionlint@v1.6.22]
      types: [yaml]
      files: "^.github/workflows/"


# #         types: ["yaml"]

# #         entry: actionlint
# #         verbose: true
#


# 
# - repo: https://github.com/rhysd/actionlint
#   rev: main
#   hooks:
#     - id: actionlint
# 
#   - repo: https://github.com/koalaman/shellcheck-precommit
#     rev: v0.9.0
#     hooks:
#     -   id: shellcheck
# 


# - repo: local # Use a local repository
#   hooks:
# #       - id: actionlint
# #         name: Lint GitHub Actions workflow files
# #         description: Runs actionlint to lint GitHub Actions workflow files
# #         language: system
# #         types: ["yaml"]
# #         files: "^.github/workflows/"
# #         entry: actionlint
# #         verbose: true
# 
#   - id: actionlint-docker
#     name: Lint GitHub Actions workflow file Docker
#     description: Runs actionlint Docker image to lint GitHub Actions workflow files
#     language: docker_image
#     types: ["yaml"]
#     files: "^.github/workflows/"
#     entry: rhysd/actionlint:1.6.22
# 
ci:
    autofix_commit_msg: |
        [pre-commit.ci] auto fixes from pre-commit.com hooks

        for more information, see https://pre-commit.ci
    autofix_prs: true
    autoupdate_branch: ''
    autoupdate_commit_msg: '[pre-commit.ci] pre-commit autoupdate'
    autoupdate_schedule: weekly
    skip: []
    submodules: false

