---
# Example compose file
version: "3.6"
services:

  helloworld-golang:
    image: 790003353990.dkr.ecr.us-east-2.amazonaws.com/orcid-us-east-2/helloworld-golang:${TAG:-1}
    build: .
    restart: ${RESTART:-no}
#     entrypoint: ${ENTRYPOINT:-"./entrypoint"}
#     env_file:
#       - ${ENV_FILE:-dev.env}
#       # anything secure that is non prod separated goes here
#       - ${DOCKER_DEV_ENV_FILE:-empty.env}
#     ports:
#       - 0.0.0.0:80:80
#       - 0.0.0.0:443:443
# 
    labels:
      description: helloworld-golang demo docker project

