name: bld_docker
run-name: ${{ inputs.docker_name }}

permissions:
  checks: write
  contents: read
  issues: read
  pull-requests: write

on:
  workflow_call:
    inputs:
      docker_name:
        description: 'Name of the docker image to build'
        required: false
        default: "orcid/version-bumping-test"
        type: string
      version_tag:
        description: 'Name of the docker tag to build'
        required: false
        default: "v2"
        type: string
      context:
        description: 'Name of the context in the repo'
        required: false
        default: "."
        type: string

  workflow_dispatch:
    inputs:
      docker_name:
        description: 'Name of the docker image to build'
        required: false
        default: "orcid/version-bumping-test"
        type: string
      version_tag:
        description: 'Name of the docker tag to build'
        required: false
        default: "next_tag"
        type: string
      context:
        description: 'Name of the context in the repo'
        required: false
        default: "."
        type: string

jobs:
  bld_docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: find next version
        id: version
        run: ./version_bump.sh
        env:
          GHA_TAG: ${{ inputs.version_tag }}

      - uses: docker/setup-buildx-action@v2
      - uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          # each cache needs a unique key for the job
          key: ${{ runner.os }}-buildx-${{ hashFiles(inputs.context) }}
          # Alternative restore keys if no exact match is found
          # I /think/ this means that other docker buildx jobs could help out here
          restore-keys: |
            ${{ runner.os }}-buildx-
      - name: Login to private registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.DOCKER_REG_PRIVATE }}
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ secrets.DOCKER_REG_PRIVATE }}/${{ inputs.docker_name}}/${{ steps.version.outputs.version_tag }}
          context: ${{ inputs.context }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache

