name: lint

permissions:
  checks: write
  contents: read
  issues: read
  pull-requests: write

on:
  workflow_call:
  workflow_dispatch:

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
    - name: blar
      run: echo 'blar'
