name: maven_test_artifact

permissions:
  checks: write
  contents: read
  issues: read
  pull-requests: write

on:
  workflow_call:
    inputs:
      context:
        description: 'Name of the context in the repo'
        required: false
        default: "."
        type: string

  workflow_dispatch:
    inputs:
      context:
        description: 'Name of the context in the repo'
        required: false
        default: "."
        type: string

jobs:
  maven_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven

      - name: "Test ${{ inputs.context }}"
        working-directory: ${{ inputs.context }}
        run: mvn --batch-mode -Dmaven.test.failure.ignore=true test

      - uses: actions/upload-artifact@v3  # upload test results
        if: success() || failure()        # run this step even if previous step failed
        with:
          name: ${{ inputs.context }}
          path: ${{ inputs.context }}/target/surefire-reports/*.xml
