name: unit_test_report

on:
  workflow_call:
    inputs:
      context:
        description: 'Name of the context in the repo'
        required: false
        default: "."
        type: string

  workflow_dispatch:
    inputs:
      context:
        description: 'Name of the context in the repo'
        required: false
        default: "."
        type: string

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
    - uses: dorny/test-reporter@v1
      with:
        artifact: ${{ inputs.context }}
        name: "${{ inputs.context }} Unit Tests"   # Name of the check run which will be created
        path: '*.xml'                              # Path to test results (inside artifact .zip)
        reporter: java-junit                       # Format of test results

